### ISSUE TITLE
Why only class Quant3Linear(nn.Module)? Does this work for 2bit, 3bit, and 4bit? I understand it is only for bit3 . Thanks

### ISSUE THREAD

**Issue by yanni-code** [jerry-chee/QuIP#11]

**Comment by jerry-chee** [comment]
We copied this from OPTQ which only implemented an efficient CUDA kernel for 3 bit weights. Please see our updated repo [QuIP#](https://github.com/Cornell-RelaxML/quip-sharp) which currently has quantization methods at 2 and 4 bits
