### ISSUE TITLE
Evaluation on LLama

### ISSUE THREAD

**Issue by NicoNico6** [jerry-chee/QuIP#2]
Hi, excellent work! 

If there is any plan for expanding the evaluation on the LLama family? what can be the expectation for QuIP and the LLama?

**Comment by NicoNico6** [comment]
## Quik Feedback.

The QuIP on OPT works well based on the READ.ME tutorials. 

But based on the [fork version](https://github.com/AlpinDale/QuIP-for-Llama), the QuIP does not fit well with LLama. The 2-bit compressed model gives a poor PPL on C4, PTB, Wikitext2

**Comment by jerry-chee** [comment]
Hey Nianhui,

Thanks for the interest and update on that fork version. I'm just getting
back from vacation, and will look into our performance on LLaMa.

Best,
Jerry

**Comment by jerry-chee** [comment]
Hi, can you share the commands you rand and the resulting numbers you are getting? I'm looking to reproduce your results then try and debug. I'm working on a separate implementation of our method on llama right now.

**Comment by yzl-eup** [comment]
I have the same poor PPL for meta-llama/llama-2-13b-hf. The command is `python llama.py llama-2-13b-hf c4 --wbits 2 --quant ldlq --incoh_processing --save llama-2-13b-hf_fp_w2.pt`. Fp16 results is 51936(wikitext2), 40732(ptb-new), 49541(c4-new) and W2 results is 106797(wikitext2), 89746(ptb-new), 99683(c4-new).

**Comment by jerry-chee** [comment]
I'm closing this since I haven't heard back and we're getting good results on llama-2 across at least 2 independent implementations between our paper co-authors. The repo will be updated with a cleaned-up version of llama-2 implementation.

**Comment by jerry-chee** [comment]
I'm closing this since I haven't heard back and we're getting good results on llama-2 across at least 2 independent implementations between our paper co-authors. The repo will be updated with a cleaned-up version of llama-2 implementation.
