### ISSUE TITLE
group-size for quip

### ISSUE THREAD

**Issue by xwuShirley** [jerry-chee/QuIP#6]
Dear author, 

thanks for the great works. While I was trying to understand your code: Quip. I wonder if we can set the groupsize of the weight?
Currently, it seems the groupsize is -1?

Best
Shirley

**Comment by jerry-chee** [comment]
Currently you can only set the group size when using the `--quant gptq` argument. However we have shown that GPTQ (now called OPTQ) and our LDLQ rounding method are equivalent, via experiments and a proof in our paper draft.

**Comment by jerry-chee** [comment]
Currently you can only set the group size when using the `--quant gptq` argument. However we have shown that GPTQ (now called OPTQ) and our LDLQ rounding method are equivalent, via experiments and a proof in our paper draft.
