### ISSUE TITLE
Do we still need to store U, V for each W

### ISSUE THREAD

**Issue by xwuShirley** [jerry-chee/QuIP#7]
Thank you very much Jerry. I have another question regarding to final size of the model. 
In standard INT4 weight, we store the scaler and the INT4 weight. 

But in your paper, since each time we have U, V matrices to transpose W. as shown in Algorithm1. Then we need to store the matrices U, V for each layer. Even though UWV^T is quantized, we still need to store U,V for each W. Given this reasoning,  how we can make the model size to be small given that we need extra memory to store U and V?

**Comment by jerry-chee** [comment]
closing issue. we're also working on a more efficient implementation
